### ISSUE TITLE
HUD Offset Issues

### ISSUE THREAD

**Issue by MajorCooke** [MajorCooke/Doom4Doom#62]
The current HUD needs a rework with alignments.

https://cdn.discordapp.com/attachments/316997265615093761/696791524884611203/Screenshot_Doom_20200406_223651.png
https://cdn.discordapp.com/attachments/316997265615093761/696791524276699266/Screenshot_Doom_20200406_223714.png

**Comment by KazumiChan495** [comment]
The second screenshot is a bigger OOF to me due to the Demon Rune blur effect being misaligned. And you know how I get when things are misaligned; it's best not to get me introduced with misalignment in things...

Anyway, the first screenshot isn't hit as bad as the second, the least that matters is that you get to see all information on your HUD. The HP/AP, ammo, Chainsaw fuel, BFG Ammo, keys, Credits, Lives, and Resistance, as well as Kill Progression.

In my Doom 2016 experiences, i've had a similar issue that caused some of the HUD elements to clip off the screen on certain resolutions. Just a comparison.

**Comment by MajorCooke** [comment]
Hmmm. Well, glad to hear I'm not the only one with this issue.

But yes. I'll look into it sometime.
